kabupaten_kota = {
    "aceh": [
        "aceh selatan",
        "aceh tenggara",
        "aceh tengah",
        "aceh timur",
        "aceh barat",
        "aceh singkil",
        "aceh jaya",
        "aceh besar",
        "pidie",
        "pidie jaya",
        "simeulue",
        "aceh utara",
        "aceh barat daya",
        "gayo lues",
        "aceh tamiang",
        "nagan raya",
        "aceh jaya",
        "bener meriah",
        "pidie jaya",
        "banda aceh",
        "sabang",
        "langsa",
        "subulussalam",
    ],
    "sumatera utara": [
        "nias",
        "mandailing natal",
        "tapanuli selatan",
        "tapanuli tengah",
        "tapanuli utara",
        "tapanuli tenggara",
        "toba samosir",
        "labuhan batu",
        "asahan",
        "simalungun",
        "dairi",
        "karo",
        "deli serdang",
        "langkat",
        "nias selatan",
        "humbang hasundutan",
        "pakpak bharat",
        "serdang bedagai",
        "batu bara",
        "padang lawas utara",
        "padang lawas",
        "labuhan batu selatan",
        "labuhan batu utara",
        "nias utara",
        "nias barat",
        "medan",
        "binjai",
        "padangsidimpuan",
        "gunungsitoli",
    ],
    "sumatera barat": [
        "solok",
        "solok selatan",
        "dharmasraya",
        "pasaman",
        "solok",
        "solok selatan",
        "dharmasraya",
        "pasaman",
        "pasaman barat",
        "limapuluh kota",
        "padang pariaman",
        "agam",
        "limapuluh kota",
        "padang pariaman",
        "agam",
        "pasaman barat",
        "padang",
        "solok",
        "sawahlunto",
        "padang panjang",
        "bukittinggi",
        "payakumbuh",
        "pariaman",
    ],
    "riau": [
        "kuantan singingi",
        "indragiri hilir",
        "indragiri hulu",
        "pelalawan",
        "siak",
        "kampar",
        "rokan hilir",
        "bengkalis",
        "rokan hulu",
        "kepulauan meranti",
        "pekanbaru",
        "dumai",
    ],
    "jambi": [
        "kerinci",
        "merangin",
        "sarolangun",
        "batang hari",
        "muaro jambi",
        "tanjung jabung barat",
        "tanjung jabung timur",
        "tebo",
        "bungo",
        "jambi",
        "sungai penuh",
    ],
    "sumatera selatan": [
        "ogan ilir",
        "muara enim",
        "lahad datu",
        "musi rawas",
        "musi banyuasin",
        "banyuasin",
        "ogan komering ilir",
        "ogan komering ulu",
        "empat lawang",
        "penukal abab lematang ilir",
        "musi rawas utara",
        "palembang",
        "prabumulih",
        "penukal abab lematang ilir",
    ],
    "bengkulu": [
        "bengkulu selatan",
        "rejang lebong",
        "bengkulu utara",
        "kaur",
        "seluma",
        "mukomuko",
        "lebong",
        "kepahiang",
        "bengkulu tengah",
        "bengkulu",
    ],
    "lampung": [
        "lampung barat",
        "tanggamus",
        "lampung selatan",
        "lampung timur",
        "lampung tengah",
        "lampung utara",
        "way kanan",
        "pesawaran",
        "pringsewu",
        "mesuji",
        "tulang bawang",
        "tulang bawang barat",
        "pesisir barat",
        "pesawaran",
        "pringsewu",
        "mesuji",
        "tulang bawang",
        "tulang bawang barat",
        "pesisir barat",
        "bandar lampung",
        "metro",
    ],
    "kepulauan bangka belitung": [
        "bangka",
        "bangka barat",
        "bangka tengah",
        "bangka selatan",
        "belitung",
        "belitung timur",
        "pangkal pinang",
    ],
    "kepulauan riau": [
        "karimun",
        "kepulauan anambas",
        "bintan",
        "natuna",
        "lingga",
        "kepulauan seribu",
        "tanjung pinang",
    ],
    "dki jakarta": [
        "kepulauan seribu",
        "jakarta",
        "d.k.i jakarta",
        "jakarta pusat",
        "jakarta utara",
        "jakarta barat",
        "jakarta selatan",
        "jakarta timur",
    ],
    "jawa barat": [
        "bogor",
        "sukaraja",
        "bekasi",
        "cianjur",
        "bandung",
        "garut",
        "tasikmalaya",
        "ciamis",
        "kuningan",
        "cirebon",
        "majalengka",
        "sumedang",
        "indramayu",
        "subang",
        "purwakarta",
        "karawang",
        "bekasi",
        "bandung barat",
        "bogor",
        "sukaraja",
        "bandung",
        "cirebon",
        "bekasi",
        "depok",
        "cimahi",
        "tasikmalaya",
        "banjar",
    ],
    "jawa tengah": [
        "cilacap",
        "brebes",
        "tegal",
        "purworejo",
        "wonosobo",
        "magelang",
        "boyolali",
        "sukoharjo",
        "wonogiri",
        "karanganyar",
        "sragen",
        "grobogan",
        "blora",
        "rembang",
        "pati",
        "kudus",
        "jepara",
        "demak",
        "semarang",
        "temanggung",
        "kendal",
        "batang",
        "pekalongan",
        "pemalang",
        "tegal",
        "brebes",
        "magelang",
        "surakarta",
        "salatiga",
        "semarang",
        "pekalongan",
        "tegal",
    ],
    "di yogyakarta": [
        "sleman",
        "d.i yogyakarta",
        "bantul",
        "gunung kidul",
        "kulon progo",
        "yogyakarta",
    ],
    "jawa timur": [
        "pacitan",
        "pati",
        "tulungagung",
        "blitar",
        "kediri",
        "malang",
        "lumajang",
        "jember",
        "banyuwangi",
        "bondowoso",
        "situbondo",
        "probolinggo",
        "pasuruan",
        "sidoarjo",
        "mojokerto",
        "jombang",
        "nganjuk",
        "madiun",
        "magetan",
        "ngawi",
        "bojonegoro",
        "tuban",
        "lamongan",
        "gresik",
        "bangkalan",
        "sampang",
        "pamekasan",
        "sumenep",
        "kediri",
        "blitar",
        "malang",
        "probolinggo",
        "pasuruan",
        "mojokerto",
        "madiun",  
        "surabaya",
        "batu",
    ],
    "banten": [
        "pandeglang",
        "lebak",
        "tangerang",
        "serang",
        "tangerang",
        "cilegon",
        "serang",
        "tangerang selatan",
    ],
    "bali": [
        "jembrana",
        "tabanan",
        "badung",
        "bangli",
        "buleleng",
        "karangasem",
        "klungkung",
        "batur",
        "kintamani",
        "denpasar",
    ],
    "nusa tenggara barat": [
        "lombok barat",
        "lombok tengah",
        "lombok timur",
        "sumbawa",
        "dompu",
        "bima",
        "sumbawa barat",
        "lombok utara",
        "mataram",
        "bima",
    ],
    "nusa tenggara timur": [
        "sumba barat",
        "sumba timur",
        "kupang",
        "timor tengah selatan",
        "timor tengah utara",
        "belu",
        "alor",
        "lembata",
        "flores timur",
        "sikka",
        "ende",
        "ngada",
        "manggarai",
        "rote ndao",
        "manggarai barat",
        "sumba tengah",
        "sumba barat daya",
        "nagekeo",
        "manggarai timur",
        "sabu raijua",
        "malaka",
        "kupang",
    ],
    "kalimantan barat": [
        "sambas",
        "bengkayang",
        "landak",
        "mempawah",
        "sanggau",
        "ketapang",
        "sintang",
        "kapuas hulu",
        "sekadau",
        "melawi",
        "kayong utara",
        "kubu raya",
        "pontianak",
        "singkawang",
    ],
    "kalimantan tengah": [
        "kotawaringin barat",
        "kotawaringin timur",
        "kapuas",
        "barito selatan",
        "barito utara",
        "sukamara",
        "lamandau",
        "seruyan",
        "katingan",
        "pulang pisau",
        "gunung mas",
        "barito timur",
        "murung raya",
        "palangka raya",
    ],
    "kalimantan selatan": [
        "tanah laut",
        "kotabaru",
        "banjar",
        "barito kuala",
        "tapin",
        "hulu sungai selatan",
        "hulu sungai tengah",
        "hulu sungai utara",
        "tabalong",
        "tanah bumbu",
        "balangan",
        "banjarmasin",
        "banjar baru",
    ],
    "kalimantan timur": [
        "paser",
        "kutai barat",
        "kutai kartanegara",
        "kutai timur",
        "berau",
        "penajam paser utara",
        "mahakam hulu",
        "balikpapan",
        "samarinda",
        "bontang",
    ],
    "kalimantan utara": [
        "bulungan",
        "malinau",
        "nunukan",
        "tana tidung",
        "tarakan",
    ],
    "sulawesi utara": [
        "bolaang mongondow",
        "minahasa",
        "kepulauan sangihe",
        "kepulauan talaud",
        "minahasa selatan",
        "minahasa utara",
        "bolaang mongondow utara",
        "minahasa tenggara",
        "bolaang mongondow selatan",
        "bolaang mongondow timur",
        "manado",
        "bitung",
        "tomohon",
        "kotamobagu",
    ],
    "sulawesi tengah": [
        "banggai kepulauan",
        "banggai",
        "morowali",
        "poso",
        "donggala",
        "toli-toli",
        "buol",
        "parigi moutong",
        "tojo una-una",
        "sigi",
        "banggai laut",
        "morowali utara",
        "palu",
    ],
    "sulawesi selatan": [
        "kepulauan selayar",
        "bulukumba",
        "bantaeng",
        "jeneponto",
        "takalar",
        "gowa",
        "sinjai",
        "maros",
        "pangkajene dan kepulauan",
        "barru",
        "bone",
        "soppeng",
        "wajo",
        "sidereng rappang",
        "pinrang",
        "enrekang",
        "luwu",
        "tana toraja",
        "luwu utara",
        "luwu timur",
        "toraja utara",
        "makassar",
        "parepare",
        "palopo",
    ],
    "sulawesi tenggara": [
        "buton",
        "muna",
        "konawe",
        "kolaka",
        "konawe selatan",
        "bombana",
        "wakatobi",
        "kolaka utara",
        "buton utara",
        "konawe utara",
        "kolaka timur",
        "konawe kepulauan",
        "muna barat",
        "buton tengah",
        "buton selatan",
        "kendari",
        "baubau",
    ],
    "gorontalo": [
        "boalemo",
        "gorontalo",
        "pohuwato",
        "bone bolango",
        "gorontalo utara",
        "gorontalo",
    ],
    "sulawesi barat": [
        "majene",
        "polewali mandar",
        "mamasa",
        "mamuju",
        "mamuju utara",
        "mamuju tengah",
        "mamuju",
    ],
    "maluku": [
        "maluku tenggara barat",
        "maluku tenggara",
        "maluku tengah",
        "buru",
        "kepulauan aru",
        "seram bagian barat",
        "seram bagian timur",
        "maluku barat daya",
        "buru selatan",
        "ambon",
        "tual",
    ],
    "maluku utara": [
        "halmahera barat",
        "halmahera tengah",
        "halmahera selatan",
        "halmahera utara",
        "halmahera timur",
        "pulau morotai",
        "pulau taliabu",
        "ternate",
        "tidore kepulauan",
        "kepulauan sula",
    ],
    "papua barat": [
        "fakfak",
        "kaimana",
        "teluk wondama",
        "teluk bintuni",
        "manokwari",
        "sorong selatan",
        "sorong",
        "raja ampat",
        "tambrauw",
        "maybrat",
        "manokwari selatan",
        "pegunungan arfak",
        "sorong",
    ],
    "papua": [
        "merauke",
        "jayawijaya",
        "jayapura",
        "nabire",
        "kepulauan yapen",
        "biak numfor",
        "paniai",
        "punca jaya",
        "mimika",
        "boven digoel",
        "mapia",
        "asmat",
        "yahukimo",
        "pegunungan bintang",
        "tolikara",
        "waropen",
        "sarmi",
        "keerom",
        "waropen utara",
        "supiori",
        "mamberamo raya",
        "nduga",
        "lanny jaya",
        "mamberano tengah",
        "yalimo",
        "puncak",
        "dogiyai",
        "intan jaya",
        "deiyai",
        "jayapura",
    ],
}

provinsi = [
"aceh",
"sumatera utara",
"sumatera barat",
"riau",
"jambi",
"sumatera selatan",
"bengkulu",
"lampung",
"kepulauan bangka belitung",
"kepulauan riau",
"dki jakarta",
"jawa barat",
"jawa tengah",
"di yogyakarta",
"jawa timur",
"banten",
"bali",
"nusa tenggara barat",
"nusa tenggara timur",
"kalimantan barat",
"kalimantan tengah",
"kalimantan selatan",
"kalimantan timur",
"kalimantan utara",
"sulawesi utara",
"sulawesi tengah",
"sulawesi selatan",
"sulawesi tenggara",
"gorontalo",
"sulawesi barat",
"maluku",
"maluku utara",
"papua barat",
"papua",
]

