# Add custom stopwords and dictionary
custom_stopwords = ['rt'
                    , 'tuh', 'biar', 'gak', 'kalo', 'juga', 'dah', 'banget', 'sama', 'an', 'siwuk', 'user', 'loh', 'and', 'mau', 'saya', 'juga',
                    'sama', 'haha', 'dengan', 'nih', 'usah', 'nya', 'ah', 'kan', 'ok', 'al', 'eh', 'deh'
                    ]

custom_dict = {'yg': 'yang',
               'gk': 'gak',
               'gantipresiden': 'ganti presiden',
               'jg': 'juga',
               'jgn': 'jangan',
               'iklanahokjahat': 'iklan ahok jahat',
               'aseng': 'asing',
               'pake': 'pakai',
               'skrg': 'sekarang',
               'sdh': 'sudah',
               'udah': 'sudah',
               'bikin': 'buat',
               'dr': 'dari',
               'china': 'cina',
               'loe': 'lu',
               'org': 'orang',
               'tp': 'tapi',
               'dg': 'dengan',
               'bgt': 'banget',
               'budha': 'buddha',
               'sm' : 'sama',
               'gin': 'jin',
               'kl': 'kalau',
               'klo': 'kalau',
               'kalo': 'kalau',
               'mrk': 'mereka',
               'elo': 'lu',
               'elu': 'lu',
               'jkw': 'jokowi',
               'kapir': 'kafir',
               'udh': 'udah',
               'msh': 'masih',
               'lg': 'lagi',
               'taik': 'tai',
               'mo': 'mau',
               'sy': 'saya',
               'goblog': 'goblok',
               'jga': 'juga',
               'luh': 'lu',
               'bangsad': 'bangsat',
               'anis': 'anies',
               'ama': 'sama',
               'kek': 'kayak',
               'jkt': 'jakarta',
               'dgn': 'dengan',
               'jd': 'jadi',
               'spt': 'seperti',
               'ni': 'nih',
               'gausa': 'gak usah',
               'mrka': 'mereka',
               'tdk': 'tidak',
               'make': 'pakai'
               }